import React from 'react';
import images from '~/assets/images';
import videos from '~/assets/videos';
// import video from '~/assets';
const Data = [
    {
        id: 1,
        name: 'JuJo Bin',
        background: images.b1,
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/7124212580931796997~c5_100x100.jpeg?x-expires=1660532400&x-signature=btEH7Ncepk4%2FwuKOXqu5QwoQSzE%3D',
        nickName: 'quynhnv',
        bio: 'Không có acc phụ. Mọi người flow em nhé ❤️',
        content: 'Thôi...không xong rồiiii haizzzz Thôi...không xong rồiiii',
        music: 'nhạc nền - Beautiful in White',
        video: 'https://v16-webapp.tiktok.com/7bac7a3f4020818ce7f88e652b38572d/62fbde5d/video/tos/useast2a/tos-useast2a-pve-0037c001-aiso/12287606b4044723b6975eac23be763f/?a=1988&ch=0&cr=0&dr=0&lr=tiktok_m&cd=0%7C0%7C1%7C0&cv=1&br=2596&bt=1298&cs=0&ds=3&ft=eXd.6Hk_Myq8ZHAOAwe2NTsTrl7Gb&mime_type=video_mp4&qs=0&rc=ODo8PDppN2lkM2VmMzg3aUBpanE6Njg6ZmhlZTMzZjgzM0BeNi42MGE1X14xNi9gNC8tYSNuNmFmcjQwZnBgLS1kL2Nzcw%3D%3D&l=20220816121336010245243133261696CB&btag=80000',
        like: 1.2,
        comments: 7.5,
        share: 10.6,
        check: true,
        viewers: 904,
    },
    {
        id: 2,
        name: 'Hoang y Nhi',
        background: images.b2,

        avatar: images.hyn,
        nickName: 'hyn_2305',
        bio: 'Không có acc phụ. Mọi người flow em nhé ❤️',
        content: 'em có hai nụ cười🍑🍑🍑',
        music: 'original sound - Babyboss🍺',
        video: videos.hyn,
        like: 408.1,
        comments: 12,
        followers: 51.4,
        following: 4,
        check: true,
        viewers: 750,
        share: 6.2,
    },
    {
        id: 3,
        name: 'Thy Thy',
        avatar: images.vanthy,
        background: images.b3,

        nickName: 'vanthyy02',
        bio: '✨Ig: vannthyy02 Fb: Vân Thy✨sIn tư đồ thì ở đây👇',
        content: 'Cuốn z là p đu ngay💃🏻',
        music: 'Tôi yêu anh từ 1 ánh nhìn - W S E A L',
        video: videos.vanthy2,
        like: 442.3,
        comments: 1234,
        share: 34,
        followers: 20.4,
        check: true,
        following: 12,
        viewers: 129,
    },
    {
        id: 4,
        nickName: 'ebe.quynh.ff',
        background: images.b4,

        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/8ff7a8e134012d4c36ea2d6a0cc8d90c~c5_100x100.jpeg?x-expires=1660615200&x-signature=Pvg0fbTz2Bk4O82EeU1XOdiNNwk%3D',
        name: '๖ۣۜҪôηɠ•Ҫɦúล ๖ۣۜHòลηɠ•Ŧửツ',
        content: 'em đâu làm gì sai đâu sao bỏ em vậy😞',
        music: 'nhạc nền - ๖ۣۜҪôηɠ•Ҫɦúล ๖ۣۜHòลηɠ•Ŧửツ',
        video: videos.v4,
        like: '556.1',
        comments: '343',
        share: '234',
        followers: 212.4,
        check: true,
        following: 12,
        viewers: 1223,
    },
    {
        id: 5,
        name: 'Tiểu Hý',
        background: images.b5,
        avatar: images.tieuhy,
        nickName: 'tieu_hy26',
        content: 'Cái ngày mà tui còn mập nè🤣',
        music: 'Hạ Còn Vương Nắng (Remix) #2 - DatKaa',
        video: videos.tieuhy,
        like: '1.3',
        bio: 'Suong qua kimochi ',
        comments: '10.4',
        share: '5.2',
        followers: 112,
        check: true,
        following: 32,
        viewers: 4958,
    },
    {
        id: 6,
        name: 'fan sam tổng mãi đỉnh 😝😝',
        background: images.b6,
        avatar: images.fansam,
        nickName: 'fanngocmatcha1344',
        content: 'hello mn',
        music: 'nhạc nền - học trò thầy Kiệt Hà Tịn  😝',
        video: videos.fansam,
        like: '1.3',
        bio: '100k fl mình sâu giọng hát',
        comments: '5.4',
        share: '7',
        followers: 45,
        check: true,
        following: 3,
        viewers: 879,
    },
    // {
    //     id: 6,
    //     name: '',
    //     avatar: '',
    //     nickName: '',
    //     content: '',
    //     music: '',
    //     video: '',
    //     like: '',
    //     comments: '',
    //     share: '',
    // },
];

export default Data;
